ShowGuide/Models/Filme.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ShowGuide.Models
{
    public class Filme
    {
        public Filme()
        {
            Categorias = new HashSet<Categoria>();
            Comentraios = new HashSet<Comentario>();
            Utilizadores = new HashSet<ApplicationUser>();
        }
        [Key]
        public int Id { get; set; }
        //titulo do filme
        [Required]
        [Display(Name = "Título")]
        public string Titulo { get; set; }

        //descrição ou sinopse do filme
        [DataType(DataType.MultilineText)]
        [Display(Name = "Descrição")]
        public string Descricao { get; set; }

        //data de lançamento ou data de estreia do filme
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Data de Lançamento")]
        public DateTime DataLancamento { get; set; }

        //Elenco do filme
        [Required]
        public string Elenco { get; set; }

        //link para o trailler do filme
        [Display(Name = "Trailler")]
        public string TraillerLink { get; set; }

        //extensão da imagem do filme
        [Display(Name = "Imagem")]
        public string ImageExtension { get; set; }

        // especifica que um filme tem vários Comentarios
        public virtual ICollection<Comentario> Comentraios { get; set; }
        // especifica que um filme tem várias Categorias
        [Required]
        public virtual ICollection<Categoria> Categorias { get; set; }
        // utilizadores que viram este filme
        public virtual ICollection<ApplicationUser> Utilizadores { get; set; }
    }
}

ShowGuide/Controllers/FilmesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using ShowGuide.Models;

namespace ShowGuide.Controllers
{
    public class FilmesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Filmes
        public ActionResult Index(int? filtroVistos = -1,string search = "")
        {
            //guarda a pesquisa no viewbag para a view poder saber que termos estão definidos
            ViewBag.search = search;
            ViewBag.filtroVistos = filtroVistos;
            //carrega querable de filmes
            IQueryable<Filme> list = db.Filmes;
            //se houver termo de pesquisa, filtra com esta
            if (!search.Equals("")) list = list.Where(f => f.Titulo.Contains(search));
            //se o utilizador estiver autenticado
            if (User.Identity.IsAuthenticated)
            {
                //carrega o id do utilizador
                string userId = User.Identity.GetUserId();
                if (filtroVistos == 0) //filtra por só filmes vistos por o utilizador
                {
                    list = list.Where(f => f.Utilizadores.Any(u => u.Id.Equals(userId)));
                }else if (filtroVistos == 1) //filtra por só filmes NÃO vistos por o utilizador
                {
                    list = list.Where(f => !f.Utilizadores.Any(u => u.Id.Equals(userId)));
                }
            }
            //devole lista de utilizadores com os filtros aplicados
            return View(list.ToList());
        }

        // GET: Filmes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null) //se não for passado o id, volta para a lista de filmes
            {
                return RedirectToAction("Index");
            }
            //carrega dados do filme
            Filme filme = db.Filmes.Find(id);
            if (filme == null)//se o filme não for encontrado volta para a lista de filmes
            {
                return RedirectToAction("Index");
            }
            //carrega os comentários ordenados por data
            filme.Comentraios = filme.Comentraios.OrderByDescending(m => m.Data).ToList();
            return View(filme);
        }

        // GET: Filmes/Create
        [Authorize(Roles = "Admin")] //dá permições ao Admin
        public ActionResult Create()
        {
            //carrega no viewbag para a view a lista de categorias
            ViewBag.Categorias = new SelectList(db.Categorias, "Id", "Nome");
            return View();
        }

        // POST: Filmes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")] //dá permições ao Admin
        public ActionResult Create([Bind(Include = "Id,Titulo,Descricao,DataLancamento,Elenco,TraillerLink")] Filme filme, HttpPostedFileBase Image, List<int> Categorias)
        {
            if (ModelState.IsValid)
            {
                //se não for passado lista de categorias
                if (Categorias == null)
                {
                    //carrega lista vazia
                    Categorias = new List<int>();
                }
                //Para adicionar Lista de categorias aos filmes
                IQueryable<Categoria> categorias = db.Categorias.Where(a => Categorias.Any(aa => a.Id == aa));
                filme.Categorias = categorias.ToList();
                //se for enviado Imagem
                if (Image != null)
                {
                    //guarda a extensão da imagem enviada
                    filme.ImageExtension = Path.GetExtension(Image.FileName);
                }
                //adiciona o filme
                db.Filmes.Add(filme);
                db.SaveChanges();
                //se for enviado, este tem de ser aqui porque o filme tem de ser adicionado primeiro
                if (Image != null)
                {
                    //guarda a imagem
                    Image.SaveAs(Path.Combine(Server.MapPath("~/Imagens/" + filme.Id + filme.ImageExtension)));
                }
                //redireciona para os detalhes do filme
                return RedirectToAction("Details", new { id = filme.Id});
            }
            //carrega no viewbag para a view a lista de categorias
            ViewBag.Categorias = new SelectList(db.Categorias, "Id", "Nome");
            //carrega no viewbag para a view a lista de categorias selecionadas
            ViewBag.sel_Categorias = Categorias;
            return View(filme);
        }

        // GET: Filmes/Edit/5
        [Authorize(Roles = "Admin")] //dá permições ao Admin
        public ActionResult Edit(int? id)
        {
            if (id == null) //se não foi passado Id, volta para a lista de filmes
            {
                return RedirectToAction("Index");
            }
            Filme filme = db.Filmes.Find(id);
            if (filme == null) //se não foi encontrado o filme, volta para a lista de filmes
            {
                return RedirectToAction("Index");
            }
            //carrega no viewbag para a view a lista de categorias
            ViewBag.Categorias = new SelectList(db.Categorias, "Id", "Nome");
            //carrega no viewbag para a view a lista de categorias selecionadas
            ViewBag.sel_Categorias = filme.Categorias.Select(i => i.Id).ToList();
            return View(filme);
        }

        // POST: Filmes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")] //dá permições ao Admin
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Titulo,Descricao,DataLancamento,Elenco,TraillerLink,ImageExtension")] Filme filme, HttpPostedFileBase Image, List<int> Categorias)
        {
            if (ModelState.IsValid)
            {
                //se não for passado lista de categorias
                if (Categorias == null)
                {
                    //carrega lista vazia
                    Categorias = new List<int>();
                }

                //get current entry from db (db is context)
                var filmeEntry = db.Entry<Models.Filme>(filme);

                //define o filme como editado
                filmeEntry.State = EntityState.Modified;

                //carrega a lista de categorias existentes para a variavel filme
                filmeEntry.Collection(i => i.Categorias).Load();

                //Para adicionar Lista de categorias aos filmes
                IQueryable<Categoria> categorias = db.Categorias.Where(a => Categorias.Any(aa => a.Id == aa));
                //adicionamos as categorias selecionadas por o utilizador
                filme.Categorias = categorias.ToList();
                
                //se foi enviado Imagem
                if (Image != null)
                {
                    //se ja existe imagem para este filme
                    if (System.IO.File.Exists(Server.MapPath("~/Imagens/" + filme.Id + filme.ImageExtension)))
                    {
                        //apaga a imagem
                        System.IO.File.Delete(Server.MapPath("~/Imagens/" + filme.Id + filme.ImageExtension));
                    }
                    //guarda a nova extensao da nova imagem
                    filme.ImageExtension = Path.GetExtension(Image.FileName);
                    //guarda a nova imagem
                    Image.SaveAs(Path.Combine(Server.MapPath("~/Imagens/" + filme.Id + filme.ImageExtension)));
                }
                //guarda as alterações
                db.SaveChanges();
                //volta para os detalhes do filme
                return RedirectToAction("Details", new { id = filme.Id});
            }
            //carrega no viewbag para a view a lista de categorias
            ViewBag.Categorias = new SelectList(db.Categorias, "Id", "Nome");
            //carrega no viewbag para a view a lista de categorias selecionadas
            ViewBag.sel_Categorias = Categorias;
            return View(filme);
        }

        // POST: Filmes/Delete/5
        [Authorize(Roles = "Admin")] //dá permições ao Admin
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            Filme filme = db.Filmes.Find(id);
            if (filme == null) //se não foi encontrado o filme, volta para a lista de filmes
            {
                return RedirectToAction("Index");
            }
            //remover todas as categorias associadas ao filme
            filme.Categorias.Clear();
            //eliminar todos os comentários associados ao filme
            List<Comentario> comentarios = filme.Comentraios.ToList();
            foreach (var comentario in comentarios)
            {
                db.Comentarios.Remove(comentario);
            }
            //Eliminar Imagem caso esta exista
            if (filme.ImageExtension != null)
            {
                //verifica se a imagem existe
                if (System.IO.File.Exists(Server.MapPath("~/Imagens/" + filme.Id + filme.ImageExtension)))
                {
                    //apaga a imagem
                    System.IO.File.Delete(Server.MapPath("~/Imagens/" + filme.Id + filme.ImageExtension));
                }
            }
            //eliminar o filme
            db.Filmes.Remove(filme);
            //guarda as alterações
            db.SaveChanges();
            return RedirectToAction("Index");
        }

ShowGuide/Views/Filmes/Create.cshtml
@model ShowGuide.Models.Filme

@{
    ViewBag.Title = "Registar um novo filme";
}

<h2>@ViewBag.Title</h2>

<hr />

@using (Html.BeginForm("Create", "Filmes", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group row">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control col-12" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.ImageExtension, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                <input type="file" name="Image" class="form-control col-12" />
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control col-12" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.DataLancamento, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.DataLancamento, new { htmlAttributes = new { @class = "form-control col-12" } })
                @Html.ValidationMessageFor(model => model.DataLancamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Elenco, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.Elenco, new { htmlAttributes = new { @class = "form-control col-12" } })
                @Html.ValidationMessageFor(model => model.Elenco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.TraillerLink, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.TraillerLink, new { htmlAttributes = new { @class = "form-control col-12" } })
                @Html.ValidationMessageFor(model => model.TraillerLink, "", new { @class = "text-danger" })
            </div>
        </div>


        @*Lista de categorias dos Filmes*@
        <div class="form-group row">
            <label class="control-label col-md-3"> Categorias do Filme:</label>
            <div class="col-md-9">
                @Html.DropDownList("Categorias", null, htmlAttributes: new { @class = "form-control col-12", Multiple = "multiple" })
                @Html.ValidationMessageFor(model => model.Categorias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <input type="submit" value="Registar" class="btn btn-primary mr-2" />
            @Html.ActionLink("Voltar", "Index", "Filme", new { @class = "btn btn-secondary" })
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ShowGuide/Views/Filmes/Details.cshtml
@model ShowGuide.Models.Filme

@{
    ViewBag.Title = Html.DisplayFor(model => model.Titulo);
}

<div>

    @Html.ActionLink("Voltar", "Index", new { }, new { @class = "btn btn-secondary mr-2" })

    @* botões para o administrador eliminar ou alterar um filme*@
    @if (User.IsInRole("Admin"))
    {
        @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary mr-2" })

        using (Html.BeginForm("Delete", "Filmes", FormMethod.Post, new { @class = "d-inline", onsubmit = "return verifyDelete();" }))
        {

            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.Id)
            <button type="submit" class="btn btn-danger">Eliminar</button>
        }
    }
</div>
<hr />
<h4>@Html.DisplayFor(model => model.Titulo)</h4>
<div class="d-md-flex flex-row">
    @* Imagem do filme *@
    <div class="imageFilme">
        <img src="~/Imagens/@Model.Id@Html.DisplayFor(model => model.ImageExtension)" />
    </div>
    @* categorias do filme *@
    <div class="d-md-flex flex-column justify-content-center ml-4">
        <div>
            <h5>@Html.DisplayNameFor(model => model.Categorias):</h5>
            <div>
                @foreach (var categoria in Model.Categorias)
                {
                    @Html.DisplayFor(model => categoria.Nome)
                    if (!categoria.Equals(Model.Categorias.Last()))
                    {<text>, </text>}
            }
            </div>
        </div>
        @* data de lançamento *@
        <div class="mt-2">
            <h5>@Html.DisplayNameFor(model => model.DataLancamento):</h5>
            <span>
                @Html.DisplayFor(model => model.DataLancamento)
            </span>
        </div>
        @* elenco do filme *@
        <div class="mt-2">
            <h5>@Html.DisplayNameFor(model => model.Elenco):</h5>
            <span>
                @Html.DisplayFor(model => model.Elenco)
            </span>
        </div>
        @* link do trailler do filme *@
        <div class="mt-2">
            <h5>@Html.DisplayNameFor(model => model.TraillerLink):</h5>

            <span>
                <a href="@Html.DisplayFor(model => model.TraillerLink)">@Html.DisplayFor(model => model.TraillerLink)</a>
            </span>
        </div>
    </div>

</div>


@* descrição ou sinopse do filme *@
<div class="card mt-4">
    <div class="card-body">
        <h5 class="card-title">@Html.DisplayNameFor(model => model.Descricao):</h5>
        <hr />
        <div class="card-text">
            @Html.DisplayFor(model => model.Descricao)
        </div>
    </div>
</div>
<br />

@* local para o utilizador introduzir um comentário *@
<div class="card pb-4">
    <div class="card-body">
        <h4 class="card-title">Comentários</h4>
        @if (Request.IsAuthenticated)
        {
            using (Html.BeginForm("CreateComentario", "Filmes", FormMethod.Post, new { }))
            {
                @Html.AntiForgeryToken()
                <div class="card-body">
                    <h5 class="card-title">Deixe um comentário</h5>
                    @Html.Hidden("FilmeId", Model.Id)
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="card-text">
                        @Html.TextArea("Texto", htmlAttributes: new { @class = "form-control col-12", required = "required" })
                    </div>
                    <br />
                    <input type="submit" value="Enviar" class="btn btn-info card-link float-right" />
                </div>
            }
        }
    </div>
</div>
@* lista de comentários *@
<div class="mt-4 mb-4">
    @foreach (var comentario in Model.Comentraios)
    {
    <div class="col-12 d-flex justify-content-start flex-column">
        @* o comentário aparece a direita ou esquerda consoante se foi o utilizador autenticado que esccreveu este *@
        <div class="card col-lg-6 mt-2 row @{
        if (User.Identity.IsAuthenticated && User.Identity.Name.Equals(comentario.Utilizador.UserName))
        {
            @Html.Raw("align-self-end");
        }
        else
        {
            @Html.Raw("align-self-start");
        }
    }">
            <div class="card-body">
                <p class="card-text multiLine">@Html.Raw(comentario.Texto)</p>
            </div>
            <hr />
            <div class="card-body d-flex justify-content-start flex-row justify-content-between">
                <span class="card-link align-self-start">@Html.Raw(comentario.Utilizador.Nome)</span>
                <span class="card-link align-self-end">@Html.Raw(comentario.Data)</span>
            </div>
        </div>
    </div>
    }
</div>

ShowGuide/Views/Filmes/Edit.cshtml
@model ShowGuide.Models.Filme

@{
    ViewBag.Title = "Editar " + Html.DisplayFor(model => model.Titulo);
}

<h2>
    Editar @ViewBag.Title</h2>
<hr />


@using (Html.BeginForm("Edit", "Filmes", FormMethod.Post, new { enctype = "multipart/form-data", @class="m-auto" }))
{
@Html.AntiForgeryToken()

<div class="form-horizontal">
 @Html.ValidationSummary(true, "", new { @class = "text-danger" })
 @Html.HiddenFor(model => model.Id)
 @Html.HiddenFor(model => model.ImageExtension)

 <div class="form-group row">
     @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-3" })
     <div class="col-md-9">
         @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control col-12" } })
         @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
     </div>
 </div>

 <div class="form-group row">
     @Html.LabelFor(model => model.ImageExtension, htmlAttributes: new { @class = "control-label col-md-3" })
     <div class="col-md-9">
         <input type="file" name="Image" />
     </div>
 </div>

 <div class="form-group row">
     @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-3" })
     <div class="col-md-9">
         @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control col-12" } })
         @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
     </div>
 </div>

 <div class="form-group row">
     @Html.LabelFor(model => model.DataLancamento, htmlAttributes: new { @class = "control-label col-md-3" })
     <div class="col-md-9">
         @Html.EditorFor(model => model.DataLancamento, new { htmlAttributes = new { @class = "form-control col-12" } })
         @Html.ValidationMessageFor(model => model.DataLancamento, "", new { @class = "text-danger" })
     </div>
 </div>

 <div class="form-group row">
     @Html.LabelFor(model => model.Elenco, htmlAttributes: new { @class = "control-label col-md-3" })
     <div class="col-md-9">
         @Html.EditorFor(model => model.Elenco, new { htmlAttributes = new { @class = "form-control col-12" } })
         @Html.ValidationMessageFor(model => model.Elenco, "", new { @class = "text-danger" })
     </div>
 </div>

 <div class="form-group row">
     @Html.LabelFor(model => model.TraillerLink, htmlAttributes: new { @class = "control-label col-md-3" })
     <div class="col-md-9">
         @Html.EditorFor(model => model.TraillerLink, new { htmlAttributes = new { @class = "form-control col-12" } })
         @Html.ValidationMessageFor(model => model.TraillerLink, "", new { @class = "text-danger" })
     </div>
 </div>

@*Lista de categorias dos Filmes*@
    <div class="form-group row">
        <label class="control-label col-md-3"> Categorias do Filme:</label>
        <div class="col-md-9">
            @Html.DropDownList("Categorias", null, htmlAttributes: new { @class = "form-control col-12", Multiple = "multiple" })
            @Html.ValidationMessageFor(model => model.Categorias, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group row">
        <input type="submit" value="Guardar" class="btn btn-primary mr-2" />
        @Html.ActionLink("Voltar", "Details", "Filmes", new { id = Model.Id }, new { @class = "btn btn-secondary" })
    </div>
    </div>
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        <script>
        $("#Categorias").val(@(Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(((List<int>)ViewBag.sel_Categorias))))).trigger('chosen:updated');
        </script>
    }

ShowGuide/Views/Filmes/Index.cshtml
@model IEnumerable<ShowGuide.Models.Filme>

@{
    ViewBag.Title = "Filmes";
}
<h2>@ViewBag.Title</h2>
@* Caixa de pesquisa*@
<div class="card">
    <div class="card-body">
        @using (Html.BeginForm("Index", "Filmes", FormMethod.Get, new { @class = "row" }))
        {
            @* Botão de registo de filmes para o administrador *@
            if (User.IsInRole("Admin"))
            {
                <div class="col-lg-2 mt-2 mb-2">
                    @Html.ActionLink("Registar", "Create", new { }, new { @class = "btn btn-primary col-12" })
                </div>
            }
            <div class="form-group col-lg mt-2 mb-2">
                <input type="search" name="search" class="form-control col-12" value="@ViewBag.search" />
            </div>
            <div class="col-lg-2  mt-2 mb-2">
                <button type="submit" class="btn btn-success col-12">Pesquisar</button>
            </div>

            @* Filtro de filmes vistos ou não visatos caso o utilizador esteja autenticado*@
            if (Request.IsAuthenticated)
            {
                <div class="col-12 text-center">
                    <div class="card">
                        <div class="form-group mb-1 mt-1">
                            <div class="form-check d-md-inline">
                                <label class="form-check-label">
                                    @Html.RadioButton("filtroVistos", -1, (int)ViewBag.filtroVistos == -1)Todos
                                </label>
                            </div>
                            <div class="form-check d-md-inline">
                                <label class="form-check-label">
                                    @Html.RadioButton("filtroVistos", 0, (int)ViewBag.filtroVistos == 0)Só os vistos
                                </label>
                            </div>
                            <div class="form-check d-md-inline">
                                <label class="form-check-label">
                                    @Html.RadioButton("filtroVistos", 1, (int)ViewBag.filtroVistos == 1)Só os não vistos
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>
@* Lista de filmes*@
<section class="row title-sizes mt-4">
    @foreach (var filme in Model)
    {
    <figure class="col-md-3 col-sm-6  pretty-figure">
        <a href="@Url.Action("Details","Filmes",new { id = filme.Id})">
            <img src="~/Imagens/@Html.DisplayFor(modelItem => filme.Id)@Html.DisplayFor(modelItem => filme.ImageExtension)" alt="Prospect (2018)"
                 class="img-responsive">
        </a>
        <figcaption class="no-rating">
            <a href="@Url.Action("Details","Filmes",new { id = filme.Id})">@Html.DisplayFor(modelItem => filme.Titulo)</a>
        </figcaption>

        @* Checkbox que indica se o utilizador viu ou não o filme *@
        @if (Request.IsAuthenticated)
        {
            <figcaption class="no-rating">
                @using (Html.BeginForm("ToggleViewed", "Filmes", FormMethod.Post))
                {
                    @Html.AntiForgeryToken();
                    @Html.HiddenFor(f => filme.Id);
                    @Html.Hidden("search", (string)ViewBag.search);
                    @Html.Hidden("filtroVistos", (int)ViewBag.filtroVistos);
                    <label class="form-check-label">
                        @Html.CheckBox("viewed", filme.Utilizadores.Any(u => u.UserName.Equals(User.Identity.Name)), new { onchange = "this.form.submit()" })
                        Visto?
                    </label>
                }
            </figcaption>
        }
    </figure>

    }

    @* Caso não exista filmes*@
    @if (Model.Count() == 0)
    {
        <div style="text-align: center;" class="w-100 mt-2">
            <h5>Não foram encontrados Filmes.</h5>
        </div>
    }
</section>